### ISSUE TITLE
Difference between k-th order filter and boosted hp filter

### ISSUE THREAD

**Issue by kpmokpmo** [zhentaoshi/Boosted_HP_filter#1]
Hi there,

We usually name 1st order filter as l1 trend filter and 2nd order filter as hp filter. Actually Tibshirani had extended the filter to k-th order in _Adaptive piecewise polynomial estimationvia trend filtering_. I didn't do any mathematic proof, but the boosted hp filter curve looks pretty close to the k-th order one. Just wondering if there is any potential relationship between them. Thanks very much!

Best,

**Comment by zhentaoshi** [comment]
Sorry for the late reply. I just saw your message today. 

The difference lies in the L1-norm or the L2-norm of the penalty. After k-th differentiation, Tibshirani uses the L1-norm. On the other hand, Whittaker (1923)'s filter uses the L2-norm after k-th differentiation. You can find an extensive discussion of Whittaker's filter in Phillips and Jin (2021): *Business cycles, trend elimination and the HP filter*.

It is not surprising that they look close, as both filters are penalized schemes for the k-th differenced time series.
